---
title: "meow"
date:  2018-04-23
------
author: Pavithra
email: Pavithradevadiga1@gmail.com
description: > Do visit my bio when you are free..:smile:

# social links
twitter_username: Pavithra devadiga
github_username:  Pavithra devadiga

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
